name: Docker Image CI

on:
  push:
    branches: ['feat-pdf']
  pull_request:
    branches: ['feat-pdf']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REPO_URL: ${{ secrets.DOCKER_REPO_URL }}
          DOCKER_NS: ${{ secrets.DOCKER_NS }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_IMG: ${{ secrets.DOCKER_IMG }}
        run: |
          [ -z "$DOCKER_NS" ] && export DOCKER_NS="$DOCKER_USER"
          [ -z "$DOCKER_IMG" ] && export DOCKER_IMG="wechatbot"
          docker build . --file Dockerfile_ai --build-arg ALIYUN=none --tag ${DOCKER_REPO_URL}/${DOCKER_NS}/${DOCKER_IMG}:latest
          echo ${DOCKER_PASSWORD} | docker login ${DOCKER_REPO_URL} --username ${DOCKER_USER} --password-stdin
          docker push ${DOCKER_REPO_URL}/${DOCKER_NS}/${DOCKER_IMG}:latest
